# 선수 데이터 전처리

##### 라이브러리 불러오기

In [10]:
import numpy as np
import pandas as pd

## 1. 데이터 전처리

##### 1.1 기존 선수 정보

#### 1.1.0 데이터 불러오기 및 확인

In [11]:
# 데이터 불러오기
data_1 = pd.read_csv('/Users/krc/Desktop/FIFA-Online-4/crawling/player_info_crawler/player_info/player_db_original.csv')
data_1.tail(3)

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price
60001,M. 구스토,12,RB,83,74\n79\n77\n79\n78\n81\n78\n81\n80\n83\n78\n83...,"특성\n슬라이딩 태클 선호, 스피드 드리블러",2003.05.19 (20세),179cm,74kg,마름,...,91,84,79,83,27,24,31,28,26,"3,700,000 BP"
60002,G. 마마르다슈빌리,12,GK,85,41\n37\n39\n37\n37\n39\n37\n39\n36\n37\n37\n37...,특성\nGK 적극적 크로스 수비,2000.09.29 (23세),199cm,88kg,마름,...,58,40,65,41,88,87,83,88,89,"3,740,000 BP"
60003,반데르송,13,RM,83,79\n83\n81\n83\n82\n83\n81\n83\n80\n82\n79\n82...,"특성\n얼리 크로스 선호, 테크니컬 드리블러",2001.06.21 (22세),180cm,74kg,마름,...,84,81,67,82,25,25,23,24,23,"3,390,000 BP"

In [12]:
# 컬럼 확인
print(data_1.columns)
print('\n'*2,'+ - '*30+'+','\n'*2)

# 결측값 확인
print(data_1.isna().sum().sort_values())

Index(['name', 'pay_side', 'position', 'overall', 'pomation', 'skill_swap',
       'etc_birth', 'etc_height', 'etc_weight', 'etc_physical', 'etc_skill',
       'etc_foot', 'etc_nation', 'Sprint_speed', 'Acceleration', 'Finishing',
       'Shot_power', 'Long_shots', 'Positioning', 'Volleys', 'Penalties',
       'Short_pass', 'Eyesight', 'Crossing', 'Long_pass', 'FK_Acc', 'Curve',
       'Dribbling', 'Ball_control', 'Agility', 'Balance', 'Reflexes',
       'Interpersonal_defense', 'Stand_tackle', 'Interception', 'Heading',
       'Slide_tackle', 'Strength', 'Stamina', 'Aggression', 'Jumping',
       'Composure', 'GK_Diving', 'GK_Handling', 'GK_Kicking', 'GK_Reflexes',
       'GK_Positioning', 'price'],
      dtype='object')


 + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - +


name                     0
Curve                    0
Dribbling                0
Ball_control             0
Agility                  0
Balance                  0
Reflexes                 0
Interpersonal_defense    0
Stand_tackle             0
Interception             0
FK_Acc                   0
Heading                  0
Strength                 0
Stamina                  0
Aggression               0
Jumping                  0
Composure                0
GK_Diving                0
GK_Handling              0
GK_Kicking               0
GK_Reflexes              0
Slide_tackle             0
Long_pass                0
Crossing                 0
Eyesight                 0
pay_side                 0
position                 0
overall                  0
pomation                 0
skill_swap               0
etc_birth                0
etc_height               0
etc_weight               0
etc_physical             0
etc_skill                0
etc_foot                 0
Sprint_speed             0
Acceleration             0
Finishing                0
Shot_power               0
Long_shots               0
Positioning              0
Volleys                  0
Penalties                0
Short_pass               0
GK_Positioning           0
price                    0
etc_nation               3
dtype: int64

#### 1.1.1 소속 국가 없는 선수들 수정

In [13]:
# 해당 선수 검색
data_1[data_1.etc_nation.isnull() ] # P. 치라이스: 독일   /   N. 오포보어: 나이지리아   /   메리 데미랄: 튀르키예

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price
11561,P. 치라이스,5,CB,64,44\n48\n46\n48\n48\n51\n51\n51\n60\n59\n64\n59...,특성\n유리몸,1993.03.14 (30세),189cm,82kg,마름,...,51,67,69,63,12,11,11,10,11,"1,010 BP"
17795,N. 오포보어,5,CDM,59,55\n55\n56\n55\n57\n56\n57\n56\n59\n57\n60\n57...,특성,1999.11.07 (24세),175cm,80kg,건장,...,67,66,78,55,10,12,11,10,15,"1,000 BP"
59895,메리 데미랄,14,CB,87,66\n63\n64\n63\n64\n65\n68\n65\n80\n77\n87\n77...,"특성\n슬라이딩 태클 선호, 파워 헤더",1998.03.05 (25세),190cm,86kg,보통,...,79,94,82,84,32,25,30,28,24,"5,040,000 BP"

In [14]:
# 수정
data_1.etc_nation.iloc[11561] = '독일'
data_1.etc_nation.iloc[17795] = '나이지리아'
data_1.etc_nation.iloc[59895] = '튀르키예'

# 확인
data_1[data_1.etc_nation.isnull() ]

/var/folders/m5/tzr8xd5j6r9225p8yycbspkw0000gn/T/ipykernel_32393/1464126522.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1.etc_nation.iloc[11561] = '독일'
/var/folders/m5/tzr8xd5j6r9225p8yycbspkw0000gn/T/ipykernel_32393/1464126522.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1.etc_nation.iloc[17795] = '나이지리아'
/var/folders/m5/tzr8xd5j6r9225p8yycbspkw0000gn/T/ipykernel_32393/1464126522.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1.etc_nation.iloc[59895] = '튀르키예'

Empty DataFrame
Columns: [name, pay_side, position, overall, pomation, skill_swap, etc_birth, etc_height, etc_weight, etc_physical, etc_skill, etc_foot, etc_nation, Sprint_speed, Acceleration, Finishing, Shot_power, Long_shots, Positioning, Volleys, Penalties, Short_pass, Eyesight, Crossing, Long_pass, FK_Acc, Curve, Dribbling, Ball_control, Agility, Balance, Reflexes, Interpersonal_defense, Stand_tackle, Interception, Heading, Slide_tackle, Strength, Stamina, Aggression, Jumping, Composure, GK_Diving, GK_Handling, GK_Kicking, GK_Reflexes, GK_Positioning, price]
Index: []

[0 rows x 48 columns]

#### 1.1.2 국가가 잘못 기입된 선수 수정

In [15]:
# ', 국가대표'라고 입력된 값 찾기
data_1[data_1.etc_nation.str.contains(', 국가대표') == True]

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,...,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price
1491,크리스티아누 호날두,26,ST,104,104\n101\n102\n101\n100\n100\n92\n100\n74\n76\...,"특성\n강철몸, 개인 플레이 선호, 중거리 슛 선호, 파워 헤더, 아웃사이드 슈팅/...",1985.02.05 (38세),187cm,83kg,보통(고유),...,96,98,107,110,13,15,17,15,19,"15,500,000,000 BP"
1497,세르히오 라모스,15,CB,88,79\n76\n78\n76\n79\n78\n82\n78\n87\n82\n88\n82...,"특성\n유리몸, 슬라이딩 태클 선호, 긴 패스 선호, 파워 헤더",1986.03.30 (37세),184cm,82kg,보통(고유),...,81,95,94,86,15,15,13,17,12,"7,860,000 BP"
1498,엑토르 에레라,13,CM,83,79\n79\n81\n79\n81\n80\n83\n80\n83\n80\n81\n80...,특성\n강철몸,1990.04.19 (33세),185cm,78kg,보통,...,94,87,79,82,20,19,19,20,21,"784,000 BP"
1500,리오넬 메시,24,RW,104,101\n104\n104\n104\n104\n103\n97\n103\n75\n77\...,"특성\n주발 선호, 예리한 감아차기, 중거리 슛 선호, 플레이 메이커, 테크니컬 드리블러",1987.06.24 (36세),170cm,72kg,마름(고유),...,93,73,85,108,16,15,13,13,14,"175,000,000 BP"
1506,카림 벤제마,24,CF,107,107\n106\n107\n106\n107\n105\n102\n105\n89\n88...,"특성\n예리한 감아차기, 중거리 슛 선호, 플레이 메이커, 테크니컬 드리블러",1987.12.19 (36세),185cm,81kg,보통,...,103,91,103,110,19,19,16,16,19,"34,800,000,000 BP"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59990,비티냐,15,CM,87,78\n86\n84\n86\n87\n86\n87\n86\n83\n83\n74\n83...,"특성\n예리한 감아차기, 화려한 개인기, 중거리 슛 선호, 플레이 메이커, 테크니컬...",2000.02.13 (23세),173cm,65kg,마름,...,84,65,67,90,28,29,25,22,22,"5,390,000 BP"
59993,F. 비르츠,17,CAM,90,82\n89\n88\n89\n90\n90\n87\n90\n77\n78\n67\n78...,"특성\n화려한 개인기, 플레이 메이커, 아웃사이드 슈팅/크로스, 칩슛 선호, 테크니...",2003.05.03 (20세),176cm,72kg,보통,...,88,74,64,89,30,30,29,26,23,"10,900,000 BP"
59995,J. 무시알라,15,CM,95,91\n96\n96\n96\n97\n96\n95\n96\n89\n90\n82\n90...,특성\n테크니컬 드리블러,2003.02.26 (20세),183cm,70kg,마름,...,94,78,74,98,31,34,33,35,33,"10,300,000 BP"
59997,A. 슈타흐,14,CM,83,81\n80\n81\n80\n81\n81\n83\n81\n84\n82\n83\n82...,특성\n중거리 슛 선호,1998.11.15 (25세),194cm,88kg,보통,...,87,81,75,77,23,29,24,26,23,"3,870,000 BP"
60000,K. 야키치,14,CDM,83,75\n73\n75\n73\n76\n75\n79\n75\n83\n79\n82\n79...,특성,1997.05.14 (26세),181cm,75kg,보통,...,93,93,74,79,25,25,21,25,25,"3,560,000 BP"

In [16]:
# 수정 및 확인
data_1.etc_nation = data_1.etc_nation.str.replace(', 국가대표','')
data_1[data_1.etc_nation.str.contains(', 국가대표') == True]

Empty DataFrame
Columns: [name, pay_side, position, overall, pomation, skill_swap, etc_birth, etc_height, etc_weight, etc_physical, etc_skill, etc_foot, etc_nation, Sprint_speed, Acceleration, Finishing, Shot_power, Long_shots, Positioning, Volleys, Penalties, Short_pass, Eyesight, Crossing, Long_pass, FK_Acc, Curve, Dribbling, Ball_control, Agility, Balance, Reflexes, Interpersonal_defense, Stand_tackle, Interception, Heading, Slide_tackle, Strength, Stamina, Aggression, Jumping, Composure, GK_Diving, GK_Handling, GK_Kicking, GK_Reflexes, GK_Positioning, price]
Index: []

[0 rows x 48 columns]

#### 1.1.3 포메이션 별 오버롤 입력 (>>안해도 됨! 성철이형 데이터 불러오기!)

In [17]:
data_1.pomation.iloc[2]

'101\n93\n97\n93\n93\n91\n85\n91\n71\n69\n68\n69\n66\n69\n66\n24'

### 1.2 시즌 & 소속팀 선수 정보

#### 1.2.0 데이터 불러오기 및 확인

In [18]:
# 데이터 불러오기
data_2 = pd.read_csv('/Users/krc/Desktop/FIFA-Online-4/crawling/player_info_crawler/player_info/player_db.csv')
data_2.tail(3)

           name  overall season team        team_now  Stamina         pk
48527   네리 도밍게스       67     21  NaN  라싱 클루브 데 아베야네다       63  321216054
48528   미구엘 반 담       56     21  NaN        세르클러 브루게       19  321216106
48529  D. 화이트해드       55     21  NaN             NaN       60  321216111

In [19]:
# 컬럼 확인
print(data_2.columns)
print('\n'*2,'+ - '*30+'+','\n'*2)

# 결측값 확인
print(data_2.isna().sum())

Index(['name', 'overall', 'season', 'team', 'team_now', 'Stamina', 'pk'], dtype='object')


 + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - +


name            0
overall         0
season          0
team        36244
team_now     9707
Stamina         0
pk              0
dtype: int64

#### 1.2.1 소속팀 없는 선수 걸러내기

In [20]:
# 현재 & 과거 소속팀 기록 둘 다 없는 선수 불러오기
temp_1 = data_2[((data_2.team.isnull()) & (data_2.team_now.isnull())) | ((data_2.team.isnull()) & (data_2.team_now == '-')) ]     # 다시 크롤링..? 
temp_1

            name  overall season team team_now  Stamina         pk
649       티아고 모타       80    NHD  NaN        -       77  201049370
661      C. 벤 사다       63    NHD  NaN        -       58  201111503
662    야로슬라프 플라실       73    NHD  NaN        -       79  201112244
669      슈테판 키슬링       77    NHD  NaN        -       79  201137262
671      로베르트 후트       76    NHD  NaN        -       82  201137785
...          ...      ...    ...  ...      ...      ...        ...
48507    F. 히어켄스       63     21  NaN      NaN       71  321215527
48514        사미르       67     21  NaN      NaN       61  321215651
48523    M. 달 헤네       59     21  NaN      NaN       71  321215938
48524  C. 스트란드버그       65     21  NaN      NaN       70  321215965
48529   D. 화이트해드       55     21  NaN      NaN       60  321216111

[8661 rows x 7 columns]

In [21]:
temp_2 = temp_1[(temp_1.season != '21') & (temp_1.season != '20')& (temp_1.season != '19')& (temp_1.season != '18')& (temp_1.season != '17')& (temp_1.season != 'LIVE')]

# temp_2.to_csv("재크롤링필요.csv", index = False)
temp_2

           name  overall   season team team_now  Stamina         pk
649      티아고 모타       80      NHD  NaN        -       77  201049370
661     C. 벤 사다       63      NHD  NaN        -       58  201111503
662   야로슬라프 플라실       73      NHD  NaN        -       79  201112244
669     슈테판 키슬링       77      NHD  NaN        -       79  201137262
671     로베르트 후트       76      NHD  NaN        -       82  201137785
...         ...      ...      ...  ...      ...      ...        ...
2544  마르셀루 고이아누       90   19TOTS  NaN      NaN       97  215216373
2564       소아리스       91   19TOTS  NaN      NaN       88  215227476
3183        사무엘       78      OTW  NaN      NaN       82  218209017
9034        정호진       71  2019KFA  NaN        -       75  295251160
9035         최준       71  2019KFA  NaN        -       77  295251161

[116 rows x 7 columns]

In [22]:
# NHD 시즌 같은 경우 클럽 소속팀이 아에 기입되지 않음 >> 다른 시즌 카드와 비교하여 기입 필요!
temp_2_re = pd.read_csv('/Users/krc/Desktop/FIFA-Online-4/modeling/data/player_reCrawling_db.csv')
temp_2_re

            pk           team  team_now
0    201049370              -       NaN
1    201111503              -       NaN
2    201112244              -       NaN
3    201137262              -       NaN
4    201137785              -       NaN
..         ...            ...       ...
111  215216373  데미르 그룹 시바스스포르       NaN
112  215227476            NaN       NaN
113  218209017      전북 현대 모터스       NaN
114  295251160              -       NaN
115  295251161              -       NaN

[116 rows x 3 columns]

In [23]:
temp_2_re.isnull().sum()

pk            0
team          2
team_now    116
dtype: int64

In [24]:
# 재크롤링 결과 저장
temp_2_result = pd.merge(temp_2,temp_2_re, how = 'inner', on=['pk'] )
temp_2_result

,name,overall,season,team_x,team_now_x,Stamina,pk,team_y,team_now_y
0,티아고 모타,80,NHD,NaN,-,77,201049370,-,NaN
1,C. 벤 사다,63,NHD,NaN,-,58,201111503,-,NaN
2,야로슬라프 플라실,73,NHD,NaN,-,79,201112244,-,NaN
3,슈테판 키슬링,77,NHD,NaN,-,79,201137262,-,NaN
4,로베르트 후트,76,NHD,NaN,-,82,201137785,-,NaN
...,...,...,...,...,...,...,...,...,...
111,마르셀루 고이아누,90,19TOTS,NaN,NaN,97,215216373,데미르 그룹 시바스스포르,NaN
112,소아리스,91,19TOTS,NaN,NaN,88,215227476,NaN,NaN
113,사무엘,78,OTW,NaN,NaN,82,218209017,전북 현대 모터스,NaN
114,정호진,71,2019KFA,NaN,-,75,295251160,-,NaN
115,최준,71,2019KFA,NaN,-,77,295251161,-,NaN

In [25]:
# 결측치 수정 & 필요없는 컬럼 제거
print(temp_2_result.isnull().sum())
print('\n'*2,'+ - '*30+'+','\n'*2)

temp_2_result.drop(columns = ['team_x','team_now_y','team_now_x'], inplace=True)
temp_2_result.team_y = temp_2_result.team_y.fillna('-')
print(temp_2_result.isnull().sum())

name            0
overall         0
season          0
team_x        116
team_now_x      8
Stamina         0
pk              0
team_y          2
team_now_y    116
dtype: int64


 + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - +


name       0
overall    0
season     0
Stamina    0
pk         0
team_y     0
dtype: int64

In [26]:
# data_2과 같은 dataframe 모양으로 수정
temp_2_result.rename(columns = {'team_y':'team_now'}, inplace=True)
temp_2_result['team'] = '-'
temp_2_result = temp_2_result[['name','overall','season','team','team_now','Stamina','pk']]
temp_2_result

          name  overall   season team       team_now  Stamina         pk
0       티아고 모타       80      NHD    -              -       77  201049370
1      C. 벤 사다       63      NHD    -              -       58  201111503
2    야로슬라프 플라실       73      NHD    -              -       79  201112244
3      슈테판 키슬링       77      NHD    -              -       79  201137262
4      로베르트 후트       76      NHD    -              -       82  201137785
..         ...      ...      ...  ...            ...      ...        ...
111  마르셀루 고이아누       90   19TOTS    -  데미르 그룹 시바스스포르       97  215216373
112       소아리스       91   19TOTS    -              -       88  215227476
113        사무엘       78      OTW    -      전북 현대 모터스       82  218209017
114        정호진       71  2019KFA    -              -       75  295251160
115         최준       71  2019KFA    -              -       77  295251161

[116 rows x 7 columns]

#### 1.2.2 팀 경력 정리 & 합쳐주기

In [27]:
# 소속팀이 기입된 데이터들
temp_3 = data_2[~(((data_2.team.isnull()) & (data_2.team_now.isnull())) | ((data_2.team.isnull()) & (data_2.team_now == '-')))]
temp_3

,name,overall,season,team,team_now,Stamina,pk
0,미첼 바이저,81,22PLA,2022 ~\n베르더 브레멘\n2018 ~ 2022\n바이엘 04 레버쿠젠\n202...,베르더 브레멘,82,511206591
1,솔리 마치,83,22PLA,2013 ~\n브라이턴 호브 앨비언,브라이턴 호브 앨비언,85,511206594
2,마테오 코바치치,90,22PLA,2019 ~\n첼시\n2015 ~ 2019\n레알 마드리드\n2018 ~ 2019\...,첼시,87,511207410
3,레안드로 트로사르,87,22PLA,2019 ~\n브라이턴 호브 앨비언\n2012 ~ 2019\nRC 겡크\n2015 ...,브라이턴 호브 앨비언,84,511207421
4,레안드로 파레데스,88,22PLA,2019 ~\n파리 생제르맹\n2022 ~\n유벤투스\n임대\n2017 ~ 2019...,유벤투스,84,511207439
...,...,...,...,...,...,...,...
48522,틴 예드바이,68,21,2021 ~\n로코모티브 모스크바\n2015 ~ 2021\n바이엘 04 레버쿠젠\n...,NaN,62,321215930
48525,L. 도스 산토스,60,21,NaN,발랑시엔 FC,67,321215969
48526,O. 베니테스,60,21,NaN,파트로나토,60,321215990
48527,네리 도밍게스,67,21,NaN,라싱 클루브 데 아베야네다,63,321216054
48528,미구엘 반 담,56,21,NaN,세르클러 브루게,19,321216106

In [73]:
# 재크롤링한 값들과 합쳐주기
temp_4 = pd.concat([temp_3,temp_2_result],axis=0)
temp_4

,name,overall,season,team,team_now,Stamina,pk
0,미첼 바이저,81,22PLA,2022 ~\n베르더 브레멘\n2018 ~ 2022\n바이엘 04 레버쿠젠\n202...,베르더 브레멘,82,511206591
1,솔리 마치,83,22PLA,2013 ~\n브라이턴 호브 앨비언,브라이턴 호브 앨비언,85,511206594
2,마테오 코바치치,90,22PLA,2019 ~\n첼시\n2015 ~ 2019\n레알 마드리드\n2018 ~ 2019\...,첼시,87,511207410
3,레안드로 트로사르,87,22PLA,2019 ~\n브라이턴 호브 앨비언\n2012 ~ 2019\nRC 겡크\n2015 ...,브라이턴 호브 앨비언,84,511207421
4,레안드로 파레데스,88,22PLA,2019 ~\n파리 생제르맹\n2022 ~\n유벤투스\n임대\n2017 ~ 2019...,유벤투스,84,511207439
...,...,...,...,...,...,...,...
111,마르셀루 고이아누,90,19TOTS,-,데미르 그룹 시바스스포르,97,215216373
112,소아리스,91,19TOTS,-,-,88,215227476
113,사무엘,78,OTW,-,전북 현대 모터스,82,218209017
114,정호진,71,2019KFA,-,-,75,295251160
115,최준,71,2019KFA,-,-,77,295251161

##### 1.2.2.1 NaN 값 정리

In [74]:
temp_4 = temp_4.fillna('-')
temp_4

,name,overall,season,team,team_now,Stamina,pk
0,미첼 바이저,81,22PLA,2022 ~\n베르더 브레멘\n2018 ~ 2022\n바이엘 04 레버쿠젠\n202...,베르더 브레멘,82,511206591
1,솔리 마치,83,22PLA,2013 ~\n브라이턴 호브 앨비언,브라이턴 호브 앨비언,85,511206594
2,마테오 코바치치,90,22PLA,2019 ~\n첼시\n2015 ~ 2019\n레알 마드리드\n2018 ~ 2019\...,첼시,87,511207410
3,레안드로 트로사르,87,22PLA,2019 ~\n브라이턴 호브 앨비언\n2012 ~ 2019\nRC 겡크\n2015 ...,브라이턴 호브 앨비언,84,511207421
4,레안드로 파레데스,88,22PLA,2019 ~\n파리 생제르맹\n2022 ~\n유벤투스\n임대\n2017 ~ 2019...,유벤투스,84,511207439
...,...,...,...,...,...,...,...
111,마르셀루 고이아누,90,19TOTS,-,데미르 그룹 시바스스포르,97,215216373
112,소아리스,91,19TOTS,-,-,88,215227476
113,사무엘,78,OTW,-,전북 현대 모터스,82,218209017
114,정호진,71,2019KFA,-,-,75,295251160
115,최준,71,2019KFA,-,-,77,295251161

##### 1.2.2.2 경력 정리

In [75]:
# 선수 팀 커리어 정리 함수
def club_career_remover(index_num):
    temp_5 = temp_4.team.iloc[index_num]
    temp_5 = temp_5.replace('임대','').replace('~','')
    temp_5 = temp_5.split('\n')
    temp_5 = list(filter(None, temp_5))

    temp_6 = []
    temp_7 = ''
    for x in range(len(temp_5)):
        if temp_5[0].startswith('1') or temp_5[0].startswith('2'):
            if x % 2 == 1:
                temp_6.append(temp_5[x])
        else:
            if x % 2 == 0:
                temp_6.append(temp_5[x])
                
        
    if temp_6 == ['-']:
        temp_6 = [temp_4.team_now.iloc[index_num]]
        
    elif temp_4.team_now.iloc[index_num] == '-':
        temp_6 = temp_6
    else:
        temp_6 = temp_6 + [temp_4.team_now.iloc[index_num]]
        
    temp_6 = list(set(temp_6))
    temp_7 = ' / '.join(s for s in temp_6)
            
    return temp_7

In [76]:
# 수정
temp_4['club_career'] = '-'

for index in range(len(temp_4)):
    temp_a = club_career_remover(index)
    temp_4.club_career.iloc[index] = temp_a
    
temp_4

/var/folders/m5/tzr8xd5j6r9225p8yycbspkw0000gn/T/ipykernel_32393/1754443874.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_4.club_career.iloc[index] = temp_a

,name,overall,season,team,team_now,Stamina,pk,club_career
0,미첼 바이저,81,22PLA,2022 ~\n베르더 브레멘\n2018 ~ 2022\n바이엘 04 레버쿠젠\n202...,베르더 브레멘,82,511206591,바이에른 뮌헨 / 바이엘 04 레버쿠젠 / 베르더 브레멘 / 헤르타 베를린 / 1....
1,솔리 마치,83,22PLA,2013 ~\n브라이턴 호브 앨비언,브라이턴 호브 앨비언,85,511206594,브라이턴 호브 앨비언
2,마테오 코바치치,90,22PLA,2019 ~\n첼시\n2015 ~ 2019\n레알 마드리드\n2018 ~ 2019\...,첼시,87,511207410,디나모 자그레브 / 인테르 / 레알 마드리드 / 첼시
3,레안드로 트로사르,87,22PLA,2019 ~\n브라이턴 호브 앨비언\n2012 ~ 2019\nRC 겡크\n2015 ...,브라이턴 호브 앨비언,84,511207421,RC 겡크 / KVC 베스테를로 / 브라이턴 호브 앨비언 / 아우트-헤버를레이 뢰번...
4,레안드로 파레데스,88,22PLA,2019 ~\n파리 생제르맹\n2022 ~\n유벤투스\n임대\n2017 ~ 2019...,유벤투스,84,511207439,엠폴리 / 보카 주니어스 / 키에보 베로나 / 제니트 / 로마 FC / 파리 생제르...
...,...,...,...,...,...,...,...,...
111,마르셀루 고이아누,90,19TOTS,-,데미르 그룹 시바스스포르,97,215216373,데미르 그룹 시바스스포르
112,소아리스,91,19TOTS,-,-,88,215227476,-
113,사무엘,78,OTW,-,전북 현대 모터스,82,218209017,전북 현대 모터스
114,정호진,71,2019KFA,-,-,75,295251160,-
115,최준,71,2019KFA,-,-,77,295251161,-

In [77]:
temp_4.drop(columns=['team','team_now'], inplace=True)
temp_4

,name,overall,season,Stamina,pk,club_career
0,미첼 바이저,81,22PLA,82,511206591,바이에른 뮌헨 / 바이엘 04 레버쿠젠 / 베르더 브레멘 / 헤르타 베를린 / 1....
1,솔리 마치,83,22PLA,85,511206594,브라이턴 호브 앨비언
2,마테오 코바치치,90,22PLA,87,511207410,디나모 자그레브 / 인테르 / 레알 마드리드 / 첼시
3,레안드로 트로사르,87,22PLA,84,511207421,RC 겡크 / KVC 베스테를로 / 브라이턴 호브 앨비언 / 아우트-헤버를레이 뢰번...
4,레안드로 파레데스,88,22PLA,84,511207439,엠폴리 / 보카 주니어스 / 키에보 베로나 / 제니트 / 로마 FC / 파리 생제르...
...,...,...,...,...,...,...
111,마르셀루 고이아누,90,19TOTS,97,215216373,데미르 그룹 시바스스포르
112,소아리스,91,19TOTS,88,215227476,-
113,사무엘,78,OTW,82,218209017,전북 현대 모터스
114,정호진,71,2019KFA,75,295251160,-
115,최준,71,2019KFA,77,295251161,-

### 2. 두 데이터 합치기

In [78]:
# 'name','overall','Stamina' 기준으로 합치기
data_merge = pd.merge(data_1,temp_4, how = 'inner', on=['name','overall','Stamina'] )
data_merge

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,etc_skill,etc_foot,etc_nation,Sprint_speed,Acceleration,Finishing,Shot_power,Long_shots,Positioning,Volleys,Penalties,Short_pass,Eyesight,Crossing,Long_pass,FK_Acc,Curve,Dribbling,Ball_control,Agility,Balance,Reflexes,Interpersonal_defense,Stand_tackle,Interception,Heading,Slide_tackle,Strength,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price,season,pk,club_career
0,크리스티안 겐트너,20,LM,99,98\n97\n98\n97\n97\n99\n99\n99\n99\n99\n98\n99...,"특성\n유리몸, 슬라이딩 태클 선호",1985.08.14 (38세),189cm,81kg,보통,★★★,L4 – R5,독일,97,86,89,106,95,101,90,89,96,97,99,97,77,94,104,102,82,92,106,101,94,104,96,슬라이딩 태클\n94,102,109,96,90,96,12,10,23,22,27,"38,600,000 BP",UP,246158856,FC 루체른 / VfB 슈투트가르트 / VfL 볼프스부르크 / 1. FC 우니온 베를린
1,하비 가르시아,18,CDM,95,88\n86\n88\n86\n88\n88\n92\n88\n95\n91\n95\n91...,특성\n파워 헤더,1987.02.08 (36세),185cm,80kg,보통,★★★,L3 – R5,스페인,86,83,76,96,90,81,62,80,96,86,76,96,83,85,86,98,83,92,90,93,93,94,100,슬라이딩 태클\n92,97,105,106,105,94,9,14,24,11,18,"13,500,000 BP",UP,246161754,맨체스터 시티 / 카스티야 / 보아비스타 / SL 벤피카 / 제니트 / 레알 베티스...
2,요렌테,21,ST,101,101\n93\n97\n93\n93\n91\n85\n91\n71\n69\n68\n6...,특성\n파워 헤더,1985.02.26 (38세),195cm,90kg,보통,★★★,L3 – R5,스페인,87,87,110,92,86,110,91,96,90,80,67,77,60,87,94,103,82,100,99,47,34,38,112,슬라이딩 태클\n35,109,90,103,94,100,14,23,26,9,13,"63,800,000 BP",UP,246162131,나폴리 FC / SD 에이바르 / 유벤투스 / CD 바스코니아 / 아틀레틱 클럽 빌...
3,무사 뎀벨레,20,CF,98,97\n97\n98\n97\n97\n97\n93\n97\n86\n86\n82\n86...,"특성\n화려한 개인기, 중거리 슛 선호, 테크니컬 드리블러",1987.07.16 (36세),185cm,78kg,보통,★★★★,L5 – R4,벨기에,100,98,95,98,98,92,95,84,94,85,84,93,77,86,108,111,95,109,90,76,72,70,90,슬라이딩 태클\n70,101,97,85,87,109,27,24,22,12,26,"19,100,000 BP",UP,246162240,광저우 시티 / AZ / 풀럼 / K 베이르스호트 VA / 빌렘 II / 토트넘 홋스퍼
4,K. 엘아흐마디,17,CM,95,87\n89\n90\n89\n92\n90\n95\n90\n95\n91\n91\n91...,특성\n중거리 슛 선호,1985.01.27 (38세),179cm,78kg,보통,★★★,L2 – R5,모로코,81,86,78,92,88,84,78,90,100,93,79,101,69,86,91,98,92,85,96,81,93,98,81,슬라이딩 태클\n91,91,94,100,86,93,14,17,20,13,25,"8,740,000 BP",UP,246162329,페예노르트 / 알아흘리 두바이 / 알이티하드 / 애스턴 빌라 / FC 트벤터
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41030,A. 크나우프,13,RM,84,79\n85\n83\n85\n83\n84\n79\n84\n72\n76\n67\n76...,특성\n스피드 드리블러,2002.01.10 (21세),180cm,73kg,마름,★★★,L3 – R5,독일,96,97,75,75,74,83,73,55,85,82,81,68,57,79,90,86,89,85,81,67,61,65,61,슬라이딩 태클\n58,65,83,67,75,76,26,30,30,25,31,"2,830,000 BP",22PLA,511257540,아인트라흐트 프랑크푸르트 / 보루시아 도르트문트
41031,K. 야키치,14,CDM,83,75\n73\n75\n73\n76\n75\n79\n75\n83\n79\n82\n79...,특성,1997.05.14 (26세),181cm,75kg,보통,★★,L3 – R5,크로아티아,65,84,63,87,79,67,70,60,81,75,62,83,57,53,74,83,73,83,81,80,84,81,78,슬라이딩 태클\n81,89,93,93,74,79,25,25,21,25,25,"3,560,000 BP",22PLA,511257889,디나모 자그레브 / NK 이스트라 / NK 로코모티바 자그레브 / RNK 스플리트 ...
41032,M. 구스토,12,RB,83,74\n79\n77\n79\n78\n81\n78\n81\n80\n83\n78\n83...,"특성\n슬라이딩 태클 선호, 스피드 드리블러",2003.05.19 (20세),179cm,74kg,마름,★★★,L3 – R5,프랑스,96,93,58,72,59,80,65,59,82,75,87,74,51,79,80,82,83,85,81,76,82,77,69,슬라이딩 태클\n83,76,91,84,79,83,27,24,31,28,26,"3,700,000 BP",22PLA,511259307,올랭피크 리옹
41033,G. 마마르다슈빌리,12,GK,85,41\n37\n39\n37\n37\n39\n37\n39\n36\n37\n37\n37...,특성\nGK 적극적 크로스 수비,2000.09.29 (23세),199cm,88kg,마름,★,L5 – R3,조지아,60,60,26,67,24,25,24,27,31,48,29,31,26,27,27,37,49,41,69,22,28,25,30,슬라이딩 태클\n26,83,58,40,65,41,88,87,83,88,89,"3,740,000 BP",22PLA,511262621,발렌시아 CF / 디나모 트빌리시 / FC 로코모티브 / 메탈루르기 루스타비
41034,반데르송,13,RM,83,79\n83\n81\n83\n82\n83\n81\n83\n80\n82\n79\n82...,"특성\n얼리 크로스 선호, 테크니컬 드리블러",2001.06.21 (22세),180cm,74kg,마름,★★★,L3 – R5,브라질,87,88,74,73,70,83,72,61,85,83,86,77,82,79,85,84,85,83,83,79,81,77,78,슬라이딩 태클\n79,77,84,81,67,82,25,25,23,24,23,"3,390,000 BP",22PLA,511263781,그레미우 / AS 모나코

In [79]:
# 결측값 확인
print(data_merge.isna().sum().sort_values())

name                     0
Dribbling                0
Ball_control             0
Agility                  0
Balance                  0
Reflexes                 0
Interpersonal_defense    0
Stand_tackle             0
Interception             0
Heading                  0
Slide_tackle             0
Curve                    0
Strength                 0
Aggression               0
Jumping                  0
Composure                0
GK_Diving                0
GK_Handling              0
GK_Kicking               0
GK_Reflexes              0
GK_Positioning           0
price                    0
season                   0
Stamina                  0
pk                       0
FK_Acc                   0
Crossing                 0
pay_side                 0
position                 0
overall                  0
pomation                 0
skill_swap               0
etc_birth                0
etc_height               0
etc_weight               0
etc_physical             0
etc_skill                0
Long_pass                0
etc_foot                 0
Sprint_speed             0
Acceleration             0
Finishing                0
Shot_power               0
Long_shots               0
Positioning              0
Volleys                  0
Penalties                0
Short_pass               0
Eyesight                 0
etc_nation               0
club_career              0
dtype: int64

In [80]:
# 출력 갯수 제한 해제
pd.set_option('display.max_columns',None)


# 원래대로
# pd.options.display.max_columns = 20


data_merge.head(7)

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,etc_skill,etc_foot,etc_nation,Sprint_speed,Acceleration,Finishing,Shot_power,Long_shots,Positioning,Volleys,Penalties,Short_pass,Eyesight,Crossing,Long_pass,FK_Acc,Curve,Dribbling,Ball_control,Agility,Balance,Reflexes,Interpersonal_defense,Stand_tackle,Interception,Heading,Slide_tackle,Strength,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price,season,pk,club_career
0,크리스티안 겐트너,20,LM,99,98\n97\n98\n97\n97\n99\n99\n99\n99\n99\n98\n99...,"특성\n유리몸, 슬라이딩 태클 선호",1985.08.14 (38세),189cm,81kg,보통,★★★,L4 – R5,독일,97,86,89,106,95,101,90,89,96,97,99,97,77,94,104,102,82,92,106,101,94,104,96,슬라이딩 태클\n94,102,109,96,90,96,12,10,23,22,27,"38,600,000 BP",UP,246158856,FC 루체른 / VfB 슈투트가르트 / VfL 볼프스부르크 / 1. FC 우니온 베를린
1,하비 가르시아,18,CDM,95,88\n86\n88\n86\n88\n88\n92\n88\n95\n91\n95\n91...,특성\n파워 헤더,1987.02.08 (36세),185cm,80kg,보통,★★★,L3 – R5,스페인,86,83,76,96,90,81,62,80,96,86,76,96,83,85,86,98,83,92,90,93,93,94,100,슬라이딩 태클\n92,97,105,106,105,94,9,14,24,11,18,"13,500,000 BP",UP,246161754,맨체스터 시티 / 카스티야 / 보아비스타 / SL 벤피카 / 제니트 / 레알 베티스...
2,요렌테,21,ST,101,101\n93\n97\n93\n93\n91\n85\n91\n71\n69\n68\n6...,특성\n파워 헤더,1985.02.26 (38세),195cm,90kg,보통,★★★,L3 – R5,스페인,87,87,110,92,86,110,91,96,90,80,67,77,60,87,94,103,82,100,99,47,34,38,112,슬라이딩 태클\n35,109,90,103,94,100,14,23,26,9,13,"63,800,000 BP",UP,246162131,나폴리 FC / SD 에이바르 / 유벤투스 / CD 바스코니아 / 아틀레틱 클럽 빌...
3,무사 뎀벨레,20,CF,98,97\n97\n98\n97\n97\n97\n93\n97\n86\n86\n82\n86...,"특성\n화려한 개인기, 중거리 슛 선호, 테크니컬 드리블러",1987.07.16 (36세),185cm,78kg,보통,★★★★,L5 – R4,벨기에,100,98,95,98,98,92,95,84,94,85,84,93,77,86,108,111,95,109,90,76,72,70,90,슬라이딩 태클\n70,101,97,85,87,109,27,24,22,12,26,"19,100,000 BP",UP,246162240,광저우 시티 / AZ / 풀럼 / K 베이르스호트 VA / 빌렘 II / 토트넘 홋스퍼
4,K. 엘아흐마디,17,CM,95,87\n89\n90\n89\n92\n90\n95\n90\n95\n91\n91\n91...,특성\n중거리 슛 선호,1985.01.27 (38세),179cm,78kg,보통,★★★,L2 – R5,모로코,81,86,78,92,88,84,78,90,100,93,79,101,69,86,91,98,92,85,96,81,93,98,81,슬라이딩 태클\n91,91,94,100,86,93,14,17,20,13,25,"8,740,000 BP",UP,246162329,페예노르트 / 알아흘리 두바이 / 알이티하드 / 애스턴 빌라 / FC 트벤터
5,주앙 무티뉴,21,CM,100,96\n99\n99\n99\n100\n100\n100\n100\n97\n97\n92...,"특성\n강철몸, 플레이 메이커",1986.09.08 (37세),171cm,75kg,보통,★★★,L4 – R5,포르투갈,94,96,88,105,97,97,89,93,105,98,100,108,103,102,104,107,102,110,97,96,93,82,90,슬라이딩 태클\n94,85,102,98,96,104,10,17,11,12,20,"41,000,000 BP",UP,246162347,스포르팅 CP U-23 / 스포르팅 CP / 울버햄프턴 원더러스 / AS 모나코 /...
6,홀란두,19,CB,98,77\n74\n76\n74\n78\n77\n84\n77\n93\n88\n98\n88...,특성\n파워 헤더,1985.08.31 (38세),190cm,80kg,마름,★★,L3 – R5,포르투갈,87,88,60,81,69,49,60,60,91,83,58,91,64,63,73,79,78,83,98,101,102,93,104,슬라이딩 태클\n102,102,88,97,90,86,27,23,24,13,14,"18,000,000 BP",UP,246163083,나폴리 FC / 올랭피크 마르세유 / 브라가 / 인테르 / 안데를레흐트 / 벨레넨세...

In [81]:
birth = []
height = []
weight = []
star = []
sliding_tackle = []
prefer_foot = []
price_non_bp = []

for index in range(len(data_merge)):
    # 개인기 등급
    temp_num_1 = str(len(data_merge.etc_skill.iloc[index]))
    star.append(temp_num_1)
    
    # 슬라이딩 태클
    temp_num_2 = data_merge.Slide_tackle.iloc[index].split('\n')[-1]
    sliding_tackle.append(temp_num_2)
    
    # 주발 설정
    if data_merge.etc_foot.iloc[index].split(' – ')[0][-1] == data_merge.etc_foot.iloc[index].split(' – ')[1][-1]:
        prefer_foot.append('both')
    elif data_merge.etc_foot.iloc[index].split(' – ')[0][-1] > data_merge.etc_foot.iloc[index].split(' – ')[1][-1]:
        prefer_foot.append('left')
    else:
        prefer_foot.append('right')
        
    # 생일
    birth.append(data_merge.etc_birth.iloc[index].split('(')[0].rstrip())
    
    # 키
    height.append(data_merge.etc_height.iloc[index].split('c')[0])
    
    # 몸무게
    weight.append(data_merge.etc_weight.iloc[index].split('k')[0])
    
    price_non_bp.append(data_merge.price.iloc[index].split('B')[0])

In [82]:
# 수정된 값으로 기입
data_merge.Slide_tackle = sliding_tackle
data_merge.etc_skill = star
data_merge.etc_foot = prefer_foot
data_merge.etc_birth = birth
data_merge.etc_height = height
data_merge.etc_weight = weight
data_merge.price = price_non_bp

data_merge.head(7)

,name,pay_side,position,overall,pomation,skill_swap,etc_birth,etc_height,etc_weight,etc_physical,etc_skill,etc_foot,etc_nation,Sprint_speed,Acceleration,Finishing,Shot_power,Long_shots,Positioning,Volleys,Penalties,Short_pass,Eyesight,Crossing,Long_pass,FK_Acc,Curve,Dribbling,Ball_control,Agility,Balance,Reflexes,Interpersonal_defense,Stand_tackle,Interception,Heading,Slide_tackle,Strength,Stamina,Aggression,Jumping,Composure,GK_Diving,GK_Handling,GK_Kicking,GK_Reflexes,GK_Positioning,price,season,pk,club_career
0,크리스티안 겐트너,20,LM,99,98\n97\n98\n97\n97\n99\n99\n99\n99\n99\n98\n99...,"특성\n유리몸, 슬라이딩 태클 선호",1985.08.14,189,81,보통,3,right,독일,97,86,89,106,95,101,90,89,96,97,99,97,77,94,104,102,82,92,106,101,94,104,96,94,102,109,96,90,96,12,10,23,22,27,"38,600,000",UP,246158856,FC 루체른 / VfB 슈투트가르트 / VfL 볼프스부르크 / 1. FC 우니온 베를린
1,하비 가르시아,18,CDM,95,88\n86\n88\n86\n88\n88\n92\n88\n95\n91\n95\n91...,특성\n파워 헤더,1987.02.08,185,80,보통,3,right,스페인,86,83,76,96,90,81,62,80,96,86,76,96,83,85,86,98,83,92,90,93,93,94,100,92,97,105,106,105,94,9,14,24,11,18,"13,500,000",UP,246161754,맨체스터 시티 / 카스티야 / 보아비스타 / SL 벤피카 / 제니트 / 레알 베티스...
2,요렌테,21,ST,101,101\n93\n97\n93\n93\n91\n85\n91\n71\n69\n68\n6...,특성\n파워 헤더,1985.02.26,195,90,보통,3,right,스페인,87,87,110,92,86,110,91,96,90,80,67,77,60,87,94,103,82,100,99,47,34,38,112,35,109,90,103,94,100,14,23,26,9,13,"63,800,000",UP,246162131,나폴리 FC / SD 에이바르 / 유벤투스 / CD 바스코니아 / 아틀레틱 클럽 빌...
3,무사 뎀벨레,20,CF,98,97\n97\n98\n97\n97\n97\n93\n97\n86\n86\n82\n86...,"특성\n화려한 개인기, 중거리 슛 선호, 테크니컬 드리블러",1987.07.16,185,78,보통,4,left,벨기에,100,98,95,98,98,92,95,84,94,85,84,93,77,86,108,111,95,109,90,76,72,70,90,70,101,97,85,87,109,27,24,22,12,26,"19,100,000",UP,246162240,광저우 시티 / AZ / 풀럼 / K 베이르스호트 VA / 빌렘 II / 토트넘 홋스퍼
4,K. 엘아흐마디,17,CM,95,87\n89\n90\n89\n92\n90\n95\n90\n95\n91\n91\n91...,특성\n중거리 슛 선호,1985.01.27,179,78,보통,3,right,모로코,81,86,78,92,88,84,78,90,100,93,79,101,69,86,91,98,92,85,96,81,93,98,81,91,91,94,100,86,93,14,17,20,13,25,"8,740,000",UP,246162329,페예노르트 / 알아흘리 두바이 / 알이티하드 / 애스턴 빌라 / FC 트벤터
5,주앙 무티뉴,21,CM,100,96\n99\n99\n99\n100\n100\n100\n100\n97\n97\n92...,"특성\n강철몸, 플레이 메이커",1986.09.08,171,75,보통,3,right,포르투갈,94,96,88,105,97,97,89,93,105,98,100,108,103,102,104,107,102,110,97,96,93,82,90,94,85,102,98,96,104,10,17,11,12,20,"41,000,000",UP,246162347,스포르팅 CP U-23 / 스포르팅 CP / 울버햄프턴 원더러스 / AS 모나코 /...
6,홀란두,19,CB,98,77\n74\n76\n74\n78\n77\n84\n77\n93\n88\n98\n88...,특성\n파워 헤더,1985.08.31,190,80,마름,2,right,포르투갈,87,88,60,81,69,49,60,60,91,83,58,91,64,63,73,79,78,83,98,101,102,93,104,102,102,88,97,90,86,27,23,24,13,14,"18,000,000",UP,246163083,나폴리 FC / 올랭피크 마르세유 / 브라가 / 인테르 / 안데를레흐트 / 벨레넨세...

In [91]:
# 저장
# data_merge.to_csv('result_version_2.csv')

In [ ]:
'''
<team.nation>
'etc_nation'
'etc_nation'_pk

<team.club>
'club_career'
'club_career'_pk

<player.merge>
'etc_nation'_pk
'club_career'_pk
'name'
api_num_pk

<player_season>
api_num_pk
'season'
'season'_pk
 
<player.season_stats> 
'season'_pk
'reinforcement'
season

'pay_side', 
'position', 
'overall', 
'pomation', 
'Sprint_speed', 
'Acceleration', 
'Finishing',
'Shot_power', 
'Long_shots', 
'Positioning', 
'Volleys', 
'Penalties',
'Short_pass',
'Eyesight', 
'Crossing',
'Long_pass',
'FK_Acc', 
'Curve',
'Dribbling', 
'Ball_control',
'Agility', 
'Balance', 
'Reflexes',
'Interpersonal_defense', 
'Stand_tackle',
'Interception',
'Heading',
'Slide_tackle',
'Strength',
'Stamina',
'Aggression', 
'Jumping',
'Composure', 
'GK_Diving', 
'GK_Handling', 
'GK_Kicking', 
'GK_Reflexes',
'GK_Positioning',
 


<player.detail_swap>
'skill_swap',
'etc_birth', 
'etc_height', 
'etc_weight', 
'etc_physical', 
'etc_skill',
'etc_foot', 

    
<player.change>
'price'_pk
'price'

'''